### ISSUE TITLE
copy Array Items in Copy Constructor 

### ISSUE THREAD

**Issue by afshinra** [AndreasFagschlunger/O2Xfs#12]
Hi,
In Copy Constructors for classes with Array field , there is no implementation for array items and only TODO comments left,( for example "guidLights" field in "WFSPINCAPS" class )

what is your suggestion to copy array ?

**Comment by AndreasFagschlunger** [comment]
I would suggest to add a put-Method to the Array-Class which accepts a Array from the same type. I don't have a workspace running right now, but it may be a problem that there is no generic put-Method on all types. So in the Array-Class you may miss a method to update the values in a generic way. A quick solution would be to move the put-Method in the sub-class DWORDArray.

I look deeper in the issue when I have the time.
