### ISSUE TITLE
Write_RAW_DATA  Function

### ISSUE THREAD

**Issue by micro24** [AndreasFagschlunger/O2Xfs#13]
Hi
Thank you for your project. I want to Write Track1,2,3 with WriteRAWDATA function,I want to use array data(First position Track1 Data,Second Position Track2 Data,Third Position Track3 Data), I use PointerArray but  when send command to XFS i get "WFS_ERR_INTERNAL_ERROR(-15)" , how can I write Tracks,Should i use Point Array? for sending command to XFS i use this code: 

       PointerArray buffer = new PointerArray(writeData.size()) ;
		buffer.allocate() ;
		for (int i=0 ; i <writeData.size() ; i++ )
		{
			buffer.get(i).pointTo(writeData.get(i)) ;
		}
		
		xfsCommand = new XfsExecuteCommand(idcService,
				IDCExecuteCommand.WRITE_RAW_DATA,
				buffer);

writeData  is:  
Write Data is ArrayList<WFSIDCCARDDATA> writeData = new ArrayList<WFSIDCCARDDATA>();

Please guidance me.

Best Regards
Farnaz

**Comment by AndreasFagschlunger** [comment]
Hy @micro24!

According to the XFS specification, the input param for the WRITE_RAW_DATA command is a "Pointer to a NULL terminated array of pointers to card data structures.". So the elements must be of type WFSIDCCARDDATA, and the PointerArray should be "writeData.size() + 1" to end with NULL.

I probably could do a test within the next 24 hours, but maybe you could solve it by yourself.

**Comment by AndreasFagschlunger** [comment]
Hy @micro24!

There is already a example in the at.o2xfs.xfs.service-Project:

at.o2xfs.xfs.service/test/at/o2xfs/xfs/service/idc/WriteRawData.java

ZList deals with the additional NULL-Pointer to determine the end of the list.

**Comment by micro24** [comment]
Hi AndreasFagschlunger 

Thank you For your answering, it resolved my problem.

Best Regards
Farnaz
