### ISSUE TITLE
Properties file

### ISSUE THREAD

**Issue by naveenpatibanda** [AndreasFagschlunger/O2Xfs#14]
Its a great resource to understand XFS and Java integration.

Can you please add XFS.properties and services.propeties to the repository ?

**Comment by AndreasFagschlunger** [comment]
Hi naveenpatibanda! (I had to copy & paste that nickname)

The xfs.properties file should contain specific configuration, the only entry needed so far was a entry for a class name of a XfsServiceLookup.class instance.

The service.properties file was used by the PropertiesServiceLookup.class, this class looked up the available service in the service.properties file.

Let me explain this further, to access a specific XFS device you need to open it - you do this by providing a logical device name. According to the XFS specification, you find all available device names in the Windows registry. But experience has shown that the registry shows far more devices as actually connected. So if you go the Registry was, handled by the RegistryServiceLookup.class (by the way), you may end up trying to open lots of devices who aren't physically connected.

So I made a way to provide a optional implementation of this "Service lookup" mechanism. By now you had to provide this specific lookup class, as you can see I did a commit and changed this behavior. Per default you don't need a xfs.properties file, and the default lookup class is SystemPropertiesServiceLookup.class. This class searches the system properties for keys which match XFS service class names (e.g. IDC, PIN, ...) and the value is a comma separated list of devices names.

So you can provide the logical device name for a IDC device by a system property like this:

-DIDC=CardReader

or PIN device like that:
-DPIN=PinPad

To also answer you original question, you have to create a xfs.properties file with a "XfsServiceLookup.Class" key and a value containing a full qualified class name for a class extending XfsServiceLookup. If this value is at.o2xfs.operator.task.xfs.PropertiesServiceLookup, you have to create a services.properties file with the XFS service class name as the key and a comma separated list of device names as the value - same as SystemPropertiesServiceLookup.

Hopefully you're pleased with my answer.

Best regards,
Andreas Fagschlunger

**Comment by naveenpatibanda** [comment]
Thank you Adreas for the details information. I was able to add these files successfully.

I have another question- I am looking at PTRRawDataTask- I see the data being passed on bytes, 27, 64 .... Is that the standard? How do we pass graphics data? 

Thanks for your help.

**Comment by AndreasFagschlunger** [comment]
Hy naveenpatibanda!

Yes, the bytes  27 64 (Hex: 1B 40) are quite a standard on receipt printers, see:

https://en.wikipedia.org/wiki/ESC/P
http://petlibrary.tripod.com/printesc.htm

So for most receipt printers you send this two bytes and some ASCII data and you have your receipt. But if you read the specification of the WFS_CMD_PTR_RAW_DATA command, it says this:

"This command is used to send raw data (a byte string of device dependent data) to the physical
device."

So what bytes you need to send depends on your device, there isn't a standard behind this command.

But there is another command: WFS_CMD_PTR_PRINT_FORM

This command uses form and media definitions for printing and the format of those are specified by the standard - see Part 3 / section 10 of the XFS specification.

So if you want to print a image, you can define a form containing a GRAPHIC field and you can specify that this field should be the same size as your media. The value for this field is usually a file name, the supported formats are vendor dependend - but BMP works most of the time.

But a form definition isn't limited to one field, you can define any number of fields and field types. You can define a form having the fields "firstName", "lastName" and "photo". In your form you define where the label is printed, ("First Name: " etc.), and where the value is printed. You pass in the field names and values to the PRINT_FORM command, e.g. firstName=Andreas,lastName=Fagschlunger,photo=C:\andreas.bmp and a media name (defines the size of the media/paper) and the printer should print out a nice form including labels, values and graphics.

Did you get the idea behind XFS form and media definitions? I hope so.

Best regards,
Andreas Fagschlunger

**Comment by naveenpatibanda** [comment]
Thanks Andreas for the detailed explanation :+1: 

I will implement PRINT_FORM and see how that goes as I am new to this XES implementation :)
