### ISSUE TITLE
Odd behavior of XFS 

### ISSUE THREAD

**Issue by pouyamoradian** [AndreasFagschlunger/O2Xfs#17]
Hi Andreas,

We used O2XFS on jdk 1.6 and at the same time we opened Wincor test tools, 
on some device like Printer the behavior was normal and device was opened successfully but on the other devices like paper scanner and ... the devices could not be open and register.
The other time we used JRE7 and first we start test application based on O2XFS and then the Wincor test tools could not even start up successfully and returns :
WFSStartUp () returned WFS_ERR_INTERNAL_ERROR,
With Same JRE we start Wincor test tools first and then our (O2XFS based) test application but an exception occurred in  our application as below:

Exception in thread "main" java.lang.UnsatisfiedLinkError: D:\TestO2XFS\at.o2xfs
.xfs.dll: A dynamic link library (DLL) initialization routine failed
        at java.lang.ClassLoader$NativeLibrary.load(Native Method)
        at java.lang.ClassLoader.loadLibrary0(Unknown Source)
        at java.lang.ClassLoader.loadLibrary(Unknown Source)
        at java.lang.Runtime.loadLibrary0(Unknown Source)
        at java.lang.System.loadLibrary(Unknown Source)
        at at.o2xfs.xfs.XfsAPI.<init>(XfsAPI.java:55)
        at at.o2xfs.xfs.XfsAPI.getInstance(XfsAPI.java:62)
        at at.o2xfs.xfs.service.XfsServiceManager.<init>(XfsServiceManager.java: 99)
        at at.o2xfs.xfs.service.XfsServiceManager.getInstance(XfsServiceManager.java:114)
        at TestMain.setUp(TestMain.java:11)
        at TestMain.main(TestMain.java:31)

Additional information:
this machine run windows 7 SP 1 and the XFSManager is GWI.

In another case we used the exact same jar file and application on windows XP SP3 and KT XFSManager but XFS behavior was normal and both application (O2XFS Base Application and Wncor test tools) run side by side without any problem.

Do you have any idea about this situation?

**Comment by AndreasFagschlunger** [comment]
Hello pouyamoradian!

Seems to be the same Issue as #16. I didn't have problems running O²Xfs Operator on Java 8 and Wincor Test tools. So I try to make a Release with my binaries so you could test if it works.

**Comment by AndreasFagschlunger** [comment]
One question, can you start two instances of the Wincor test tools? Or does the second call fail? Did you try dependencywalker.com to scan the DLLs? For example, launch Wincor Test tool and open at.o2xfs.xfs.dll with dependencywalker.

**Comment by AndreasFagschlunger** [comment]
Hello pouyamoradian!

I've just uploaded a alpha version:

https://github.com/AndreasFagschlunger/O2Xfs/releases

You can download an extract the at.o2xfs.operator.zip from there and test it in your environment. I have to copy the whole directory, but than it is possible to launch two instances.

I've I had the time I will compile the native code in linux, because it works better out of the box with older operating systems. But by now I'm short in time.

Give it a try and keep me up to date.

**Comment by pouyamoradian** [comment]
Hello Andreas,

First of all thank you for your helpful advises. 
Yes, that is the exact problem as Issue 16 and Afshin is my colleague.

I've opened two instance of Wincor test tools side by side and everything works fine,
and also i tested your new release and ours application with ours compiled version of dll both on java 8 and it works fine !

I think the problem is with java 7 because our old application with ours and yours compiled version of dll does not work with java 7 but the exact same files works fine on java 8 !

Best Regards,
Pouya
