### ISSUE TITLE
Data type question

### ISSUE THREAD

**Issue by pouyamoradian** [AndreasFagschlunger/O2Xfs#18]
Dear Andreas,

I'm developing the CIM module in your framework i wanna ask what is the best variable match for a pointer to a zero terminated list of unsigned short ?

Can i have some getter & setter example?

Best Regards,
Pouya

**Comment by AndreasFagschlunger** [comment]
Hello pouyamoradian!

Writing would be simple, you can use USHORTArray with a length greater by one. But as I checked the docs, you probably want to read the note IDs (lpusNoteIDs).

But for reading you have to do something like in ZSTR or ZList. First of all, check if lpusNoteIDs itself isn't null. If it doesn't point to null, read the first USHORT value. If it's not 0, read the next USHORT value until it is 0.

Best regards,
Andreas

**Comment by pouyamoradian** [comment]
Thanks for your answer,
I'll try it.
