### ISSUE TITLE
Warn in call back

### ISSUE THREAD

**Issue by pouyamoradian** [AndreasFagschlunger/O2Xfs#22]
Hi @AndreasFagschlunger 

It's me again,i'm seeing this log message in my log file,
i wanna ask what is 49486 message and what is happening here,

DEBUG 2016-04-27 12:57:45,525- - : -  - at.o2xfs.xfs.util.MessageHandler - callback(int, Buffer): msg=49486,lpWFSResult=at.o2xfs.win32.impl.Win32Buffer@843b79[size=4,address=E8F59E1C] 
DEBUG 2016-04-27 12:57:45,526- - : -  - at.o2xfs.xfs.util.XfsConstants - valueOf(long, Class<E>): Undefined at.o2xfs.xfs.XfsMessage constant: 49486 
WARN  2016-04-27 12:57:45,526- - : -  - at.o2xfs.xfs.util.MessageHandler - callback(int, Buffer): Unknown message: 49486 
DEBUG 2016-04-27 12:58:01,300- - : -  - at.o2xfs.xfs.service.XfsRequestWatchdog - watchOut(): Waiting for requests ... 
DEBUG 2016-04-27 13:17:03,538- - : -  - at.o2xfs.xfs.util.MessageHandler - callback(int, Buffer): msg=49486,lpWFSResult=at.o2xfs.win32.impl.Win32Buffer@b49b75[size=4,address=E8F59E1C] 
DEBUG 2016-04-27 13:17:03,538- - : -  - at.o2xfs.xfs.util.XfsConstants - valueOf(long, Class<E>): Undefined at.o2xfs.xfs.XfsMessage constant: 49486 
WARN  2016-04-27 13:17:03,538- - : -  - at.o2xfs.xfs.util.MessageHandler - callback(int, Buffer): Unknown message: 49486 
DEBUG 2016-04-27 13:18:49,090- - : -  - at.o2xfs.xfs.util.MessageHandler - callback(int, Buffer): msg=49486,lpWFSResult=at.o2xfs.win32.impl.Win32Buffer@1af4e69[size=4,address=E8F59E1C] 
DEBUG 2016-04-27 13:18:49,091- - : -  - at.o2xfs.xfs.util.XfsConstants - valueOf(long, Class<E>): Undefined at.o2xfs.xfs.XfsMessage constant: 49486 
WARN  2016-04-27 13:18:49,091- - : -  - at.o2xfs.xfs.util.MessageHandler - callback(int, Buffer): Unknown message: 49486

with regards,
Pouya

**Comment by AndreasFagschlunger** [comment]
Hi @pouyamoradian 

The MessageHandler receives every message greater than WM_USER, see [MessageHandler.cpp](https://github.com/AndreasFagschlunger/O2Xfs/blob/master/at.o2xfs.xfs/native/at.o2xfs.xfs/MessageHandler.cpp#L90). Were only a few messages are defined for XFS ([XfsMessage.java](https://github.com/AndreasFagschlunger/O2Xfs/blob/master/at.o2xfs.xfs/src/at/o2xfs/xfs/XfsMessage.java)).

So what's happening is that another process sends messages which we receive but do not understand. IMHO you can ignore the log entries. I don't know if MessageHandler should ignore other messages altogether.

Best regards,
Andreas Fagschlunger

**Comment by pouyamoradian** [comment]
Hi @AndreasFagschlunger 

Thank you for answering my question.

Best Regards,
Pouya Moradian
