### ISSUE TITLE
Question about check

### ISSUE THREAD

**Issue by pouyamoradian** [AndreasFagschlunger/O2Xfs#24]
Hi @AndreasFagschlunger

It's me again,I'm developing check module of xfs and for writing operation in this module I have to send OutputField of WFSCHKINPROCESSFORM.

As it is mentioned in documentation 
"lpszOutputFields
Pointer to a series of "<FieldName>=<FieldValue>" strings, where each string is null-terminated
with the entire field string terminating with two null characters. If lpszOutputFields contains two
null characters then no data is written (no data is endorsed and no MICR/OCR is written) "
the OutPutFields should be separated with null character and at the end should have two null character.

I'm using GWI device and the sample data is as below :

4669656C64313D9DEDFF92F9FFAAF591A4F9FF9EA79192004669656C64323D8183818381838183004669656C64333DF890A4FEA5FFAAA2004669656C64343DFF0000

(in this data it uses 00 for one null character and 0000 for two null character)

As you can see the String format of these hex character is something like:
Field1=(Some Persian character)\0Field2=......\0Field4=(Some other character)\0\0

I've test this data(the hex one) via Wincor test tools and it works, In my code I'm using LPSTR as mentioned in documentation and also I'm using pointTo(String type) to set hexString to this field but at the end it's SP will crash (because of weakness in exception handling, it should return Invalid Data Error) and it does print my data.

I wanna ask what is the problem with my code?

**Comment by AndreasFagschlunger** [comment]
Hi @pouyamoradian 

First thing you can try is to take a look at [XfsExtra.java](https://github.com/AndreasFagschlunger/O2Xfs/blob/develop/at.o2xfs.xfs/src/main/java/at/o2xfs/xfs/XfsExtra.java), it's basically a Map of Key=Value pairs where one NUL terminates the pair and two NULs end the whole data.

Another thing I want you to know, I've setup a Page for the project were I explain how to setup Eclipse with the current develop-branch, you might take a look:

http://andreasfagschlunger.github.io/O2Xfs/

With best regards,
Andreas Fagschlunger

**Comment by pouyamoradian** [comment]
Dear @AndreasFagschlunger 

First of all thank you for your quick answer, now my code is like

![untitled](https://cloud.githubusercontent.com/assets/14963731/15321852/5d812a22-1c4e-11e6-998c-4a93b8db7c9f.png)

I've just hard coded this for test, and also I've tried data.toString() instead of Hex.encode(data) but same happened and i got connection lost  !

what's your idea about it?

**Comment by AndreasFagschlunger** [comment]
Hello @pouyamoradian 

Use `XfsExtra` directly, since it's already a `Type` you can `pointTo`.
```java
this.OutputFields.pointTo(xfsExtra);
```

**Comment by pouyamoradian** [comment]
Hello @AndreasFagschlunger 
I've tried that and WFS_ERR_INVALID_DATA was received.

**Comment by AndreasFagschlunger** [comment]
Hello @pouyamoradian 

Can you provide the Traces from the Wincor Tools? Since you mentioned Persian characters, do you set any UNICODE fields? Does the SP write any log files so you can compare the call from Test Tool and Java?

**Comment by pouyamoradian** [comment]
Hi @AndreasFagschlunger 

Sorry for late reply,
I've checked SP log of the GWI but it is really messy and i could not found it's head or trail.
About UNICODE feilds i'm using IranSystem Encode (https://en.wikipedia.org/wiki/Iran_System_encoding_standard) and Sp Support it.

I think I found the problem, I have to pass a String like Field1=somethingHere'\n'File2=SomethingHere...Filed4=SomethingHere'\n''\n'

but i was sendig simething like 
Field1=somethingHere"\n"File2=SomethingHere...Filed4=SomethingHere"\n""\n"

the difference is '\n' and "\n" and i was sending this string as HexCode to SP but as i see i should send this in ASCII way, and also i was using LPSTR for this type that uses ZSTR in point to and ZSTR itself has a NUL value at the end.

Now i'm sendig the data as 
Field1=somethingHere'\n'File2=SomethingHere...Filed4=SomethingHere'\n'
and it works but in the CHKProcessFormCommand i have a field with type of WFSCHKINPROCESSFORM and i'm setting this field in constructor of CHKProcessFormCommand but i'm trying to copy input value to this value with copyConstructor asthis.data = new WFSCHKINPROCESSFORM(chkService.getXfsVersion(), data);

**Comment by AndreasFagschlunger** [comment]
I don't know which type you use for `OutputFields`, but I suggest to use `XfsExtra`:

```java
private final XfsExtra outputFields = new XfsExtra();
```
See [CdmStatus3.java](https://github.com/AndreasFagschlunger/O2Xfs/blob/develop/o2xfs-xfs3/src/o2xfs-xfs3/java/at/o2xfs/xfs/cdm/v3_00/CdmStatus3.java#L80) for example.

**Comment by pouyamoradian** [comment]
As I can see in documentation of WOSA XFS it should be LPSTR and also I've tested the XfsExtra One but i got Invalid data.
Thank you for your answer.

**Comment by AndreasFagschlunger** [comment]
`XfsExtra` extends `Pointer` so it's compatible with `LPSTR` and already used this way, see `lpszExtra` in `WFS***STATUS` structures and as before [CdmStatus3.java](https://github.com/AndreasFagschlunger/O2Xfs/blob/develop/o2xfs-xfs3/src/o2xfs-xfs3/java/at/o2xfs/xfs/cdm/v3_00/CdmStatus3.java).
