### ISSUE TITLE
unable to deploy to atm

### ISSUE THREAD

**Issue by amphibithen** [AndreasFagschlunger/O2Xfs#31]
Not sure if I'm missing something, or if it's intended to, but I am having trouble deploying this to ATM again.

I was able to get the alpha 1.0 release working, but now that I can build develop branch, most recent code seems not to run.

when i run start.cmd
```
java.lang.NoClassDefFoundError: org/slf4j/LoggerFactory
	at at.o2xfs.log.LoggerFactory.getLogger(LoggerFactory.java:39)
	at at.o2xfs.operator.O2XfsOperator.<clinit>(O2XfsOperator.java:51)
Caused by: java.lang.ClassNotFoundException: org.slf4j.LoggerFactory
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 2 more
Exception in thread "main" 
```

when i run posdemo.cmd
`no main manifest attribute, in C:\deploy\lib\at.o2xfs.emv.demo.jar`

my first step was to automate the packaging of files for deployment to atm (same output as the alpha release), which i did and would like to share, but not until it is working.  i noticed the alpha release had some common libraries in them like log4j which i can't seem to find anywhere in the project, but adding those to the lib folder does not help.

am i missing something here, or is develop branch not runnable in its current form?

**Comment by AndreasFagschlunger** [comment]
The `develop` branch currently has focus on the XFS projects, not the EMV related projects. Don't know what your goal is?

But in case of `at.o2xfs.operator`, did you use `gradlew dist` to create a distributable package? For me it creates a `at.o2xfs.operator.zip` file in `at.o2xfs.operator\build\distributions` which runs fine on a ATM after extracting and creating a `services.properties` file.

**Comment by amphibithen** [comment]
thank you, thats what i was missing `gradlew dist`.
