### ISSUE TITLE
O2 dlls log and Exception

### ISSUE THREAD

**Issue by pouyamoradian** [AndreasFagschlunger/O2Xfs#32]
Hi @AndreasFagschlunger 

As i can see there is some log file with the name of hs_err_pid*.log just at the same location of o2 dlls.
Is there any configurable parameter to modify the path of these file?
Where is it from, java side or native side?

Anther question is, can i catch Exception like EXCEPTION_ACCESS_VIOLATION from java side?
If it is possible can you explain how can i do that?

with best regards
Pouya Moradian.

**Comment by AndreasFagschlunger** [comment]
Hi @pouyamoradian! Sorry for not answering before but we moved and I'm a little busy at the time. `hs_err_pid*.log`s are bad, means something is broken. The log files are placed in the working directory, so you may change the working directory the application runs. You could also try to set the `-XX:LogFileDir` property, but I didn't found much on the topic.

I don't think is possible to catch access violations. I did read some about this topic a time ago, there may be compiler options and statements to not crash on access violations, but I didn't go any further.

The major cause for ACCESS_VIOLATIONS are NULL-pointers or other kinds of bad pointers. You should really try to find out when this happens and what causes it, maybe it's a bug in O²Xfs itself.

With best regards,
Andreas Fagschlunger

**Comment by pouyamoradian** [comment]
Thanks for your quick answer,

Yes, i know that's bad, in these case, our application and JVM will goes down and i didn't know (by reading the log),I was asking about the log file to realize the problem in out code and to find the bad codding in our device layer.

In this case problem was in the copy constructor of our WFSPTRSTATUS and I found this by running our test class and then I saw process detached in eclipse console, but unfortunately this things (process detached log) could not be logged in customer environment and may cause some ambiguity about the crash reason.

So I think I have to tell out support team to collect hs_err_pid*.log also in the path of O2 dll.

As another question is there any way to prevent java side crash after crash of native side?
Like catching some kind of Throwable exception or something?

With best regards,
Pouya Moradian

**Comment by AndreasFagschlunger** [comment]
It is actually the Java side (JVM) which is going down, since your code is executed within the JVM. What you can think of is some kind of recover, e.g. a process watchdog which restarts application if the process crashes. Or you split your application into two, where one application contains the UI logic and the other the XFS calls. For example, they can communicate over a local TCP/IP connection (Java Sockets). When the device application crashes, the UI process is still alive and may raise it again.

But best thing would be to fix O²Xfs or it's components and don't let any access violations happen. This is why I introduces native tests for structures in the newer versions of O²Xfs. So reading/writing to structures is basically checked.

**Comment by pouyamoradian** [comment]
Thanks for your help dear @AndreasFagschlunger.

I've layered app that is already separated, But I'm loading the device layer in an applet application and in case of JVM crash it goes down too.I think i have to change my architecture.

Best Regards
Pouya Moradian

**Comment by AndreasFagschlunger** [comment]
Hi @pouyamoradian.

I recently stepped over the [JNA](https://github.com/java-native-access/jna) lib again and found out the lib provides a `setProtected` method. It uses a windows feature called [Structured Exception Handling](https://msdn.microsoft.com/en-us/library/windows/desktop/ms680657(v=vs.85).aspx) which allows you to catch access violations and other hardware errors.

It's a feature which shouldn't be used in production environment, but the same thing could probably be done in O²Xfs.

**Comment by pouyamoradian** [comment]
Hi @AndreasFagschlunger 

Thanks for informing me about it,
I have to spend much time on it.
