### ISSUE TITLE
Parsing pointer to array of Long

### ISSUE THREAD

**Issue by pouyamoradian** [AndreasFagschlunger/O2Xfs#33]
Hi @AndreasFagschlunger 

As I can see in documentation, WFSCDMDENOMINATION has a field of LPULONG and it is "Pointer to an array of ULONGs", I'm trying to deal with this field az ZTList with type of ULONG but it does not work !
Every time my subBufferPointer in ZTList constructor is a null pointer and nothing will be add to list of our pointer.

My Zlist Constructor is:

public ZTList(Pointer pointer) {
		int offset = 0;
		Buffer buffer = null;
		
		while (true) {
			
			buffer = pointer.buffer(offset + pointer.getSize());
			Pointer subBufferPointer = new Pointer(buffer.subBuffer(offset, pointer.getSize()));
			
			if (Pointer.NULL.equals(subBufferPointer)) {
				break;
			}
			pointers.add(subBufferPointer);
			offset += subBufferPointer.getSize();
		}
		assignBuffer(buffer);
	}

Can I handle this kind of variable with ZList or ZTList?
As I mentioned in documentation said it is a pointer to an array list so there is no pointer after this pointer and it is only a pointer to a starting point of an array.

Do you have any idea about handling this kind of thing?

**Comment by AndreasFagschlunger** [comment]
You're correct, it says `array of ULONGs`. It doesn't say `zero-terminated list of` or `NULL-terminated array of`. So the array has a fixed size provided by the `usCount` field.

And `usCount` may indeed be 0, so `lpulValues` may point to `NULL`. Check out how I'm handling this in [Denomination3.java](https://github.com/AndreasFagschlunger/O2Xfs/blob/develop/o2xfs-xfs3/src/o2xfs-xfs3/java/at/o2xfs/xfs/cdm/v3_00/Denomination3.java#L137).

**Comment by pouyamoradian** [comment]
Dear @AndreasFagschlunger

I totally appreciate your support, I didn't have UINTArray in my version of O2Xfs and also I'm developing this layer on java 7 and there is no Optional in that so, I checked Value against null instead of isPresent and it works fine.
Thank you again.

With best regards
Pouya Moradian.

**Comment by AndreasFagschlunger** [comment]
The basic behavior of `java.util.Optional` could be written in Java 7 too, so you only have to change the import to your own version of Optional. And it has actually found it's way into Java 8 over the Google [guava](https://github.com/google/guava/wiki/UsingAndAvoidingNullExplained) lib.

```
public final class Optional<T> {

	private static final Optional<?> EMPTY = new Optional<>(null);

	private final T value;

	private Optional(final T value) {
		this.value = value;
	}

	public boolean isPresent() {
		return value != null;
	}

	public T get() {
		if (!isPresent()) {
			throw new NoSuchElementException();
		}
		return value;
	}

	public T orElse(final T other) {
		if (isPresent()) {
			return value;
		}
		return other;
	}

	@SuppressWarnings("unchecked")
	public static <T> Optional<T> empty() {
		return (Optional<T>) EMPTY;
	}

	public static <T> Optional<T> of(final T value) {
		if(value == null) {
		  throw new NullPointerException();
		}
		return new Optional<>(value);
	}

	@SuppressWarnings("unchecked")
	public static <T> Optional<T> ofNullable(final T value) {
		return value == null ? (Optional<T>) empty() : of(value);
	}
}
``´

**Comment by pouyamoradian** [comment]
Again thank you for your help.
I'll try it ;)
