### ISSUE TITLE
Question about ZeroTerminated Word Array

### ISSUE THREAD

**Issue by pouyamoradian** [AndreasFagschlunger/O2Xfs#34]
Hi @AndreasFagschlunger 

I hope you are doing well,
This time I'm developing BCR module and in the capability struct, I have 

lpwSymbologies
Pointer to an array of WORDs. This list specifies the barcode symbologies readable by the
scanner. The array is terminated with a zero value. lpwSymbologies is a NULL pointer if the
supported barcode symbologies can not be determined.

As mentioned in the documentation this pointer is pointing to a word array but I don't have have count of this array.
Do you have any solution for this case?

**Comment by AndreasFagschlunger** [comment]
Hi @pouyamoradian 

Im doing quite well, thank you. I also have some ideas what I want to do next, I want to remove the Swing UI in O²Xfs Operator and switch to a web-based UI. But the free time I have I currently spend in playing computer games :)

Regarding to your problem, you should think of a list of WORD's where the end of the list is value 0 ([1, 2, 3, 0]. So you have to determine the length yourself. It's similar to Issue #21 and I workaround this with a helper class, for example: [NoteIDs.java](https://github.com/AndreasFagschlunger/O2Xfs/blob/develop/o2xfs-xfs3/src/o2xfs-xfs3/java/at/o2xfs/xfs/cim/v3_00/NoteIDs.java#L55) used in [CashInType3.java](https://github.com/AndreasFagschlunger/O2Xfs/blob/develop/o2xfs-xfs3/src/o2xfs-xfs3/java/at/o2xfs/xfs/cim/v3_00/CashInType3.java#L80).

**Comment by pouyamoradian** [comment]
Sounds good,
I've tried that way,but the problem I have is, I was sending data to XFS and i used CashInType but now i'm receiving data from XFS and assign the data to my object via assignBuffer but all of the time my Symbologies is empty !

public BCRSymbology(Pointer aPointer) {

		WORD temp = new WORD();
		temp.allocate();

		if (Pointer.NULL.equals(aPointer)) {
			data = new WORD[0];
		} else {
			Buffer buffer = null;
			for (int i = 0;; i++) {
				buffer = aPointer.buffer((i * temp.getSize()) + temp.getSize());
				Buffer subBuffer = buffer.subBuffer(i * temp.getSize(),
						temp.getSize());
				WORD word = new WORD(subBuffer);
				if (word.intValue() == 0L) {
					data = new WORD[i];
					assignBuffer(buffer);
					break;
				}
			}
		}
	}

And at the first iteration, word.intValue() == 0L become true !!

**Comment by AndreasFagschlunger** [comment]
Hi @pouyamoradian 

As you can see in my latest commit ae5460f I added a unit test for a BCR Capabilities3_10 class. It works as expected, in the native code the test symbologies are defined like following:

```C++
static WORD wSymbologies[] = { WFS_BCR_SYM_EAN128, WFS_BCR_SYM_JAN13, 0 };
```

and the unit test output:

`at.o2xfs.xfs.bcr.v3_10.Capabilities3_10@39699c[serviceClass=15,compound=false,canFilterSymbologies=true,symbologies={EAN128,JAN13},guidLights=[[MEDIUM_FLASH, GREEN], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], [], []],extra={Key1=Value1, Key2=Value2},powerSaveControl=true]`

One last note, nothing prevents the SPI from sending you a DWORD array containing only a zero value - practically an empty list (but not NULL). Do you know for sure the list contains values?

**Comment by pouyamoradian** [comment]
Hi @AndreasFagschlunger 

I know, I think something is wrong with my code,
I've tested this info command with Wincor test tools, and the returned value is not null.
In my code i get some Pointer Type with an address and it seems it is null !
I think I have to check my code again.

thank you
