### ISSUE TITLE
Get Event from Pin

### ISSUE THREAD

**Issue by azdafirmansyah** [AndreasFagschlunger/O2Xfs#47]
Hi All,

I try to get event from pin but still not success.
1. What is different between `GetPINCommand` (I get error `WFS_ERR_PIN_KEYNOTSUPPORTED` using this) and `PINGetDataCommand`?
2. which one to capture all pin event ?

Regards,
Azda Firmansyah

**Comment by AndreasFagschlunger** [comment]
Hello @azdafirmansyah!

The `GET_DATA` command is used to read user input from the PIN Pad, e.g. to navigate through the application (check `PINInputDevice`). `GET_PIN` enables a secure PIN entry, where you're only informed that keys are pressed but not actually which ones. Usually you execute `GET_PINBLOCK` afterwards to get the encrypted PIN which then can be verified by a ICC or online host (e.g. `XfsPINPadImpl`).

**Comment by azdafirmansyah** [comment]
Thanks @AndreasFagschlunger,
