### ISSUE TITLE
services.properties file name is mismatch

### ISSUE THREAD

**Issue by jifffffy** [AndreasFagschlunger/O2Xfs#50]
Hi, I found [https://github.com/AndreasFagschlunger/O2Xfs/blob/develop/at.o2xfs.operator/src/main/java/at/o2xfs/operator/task/xfs/PropertiesServiceLookup.java
](url) load the name of file is 'service.properties'.
but [https://github.com/AndreasFagschlunger/O2Xfs/blob/develop/at.o2xfs.xfs.service/src/main/java/at/o2xfs/xfs/service/lookup/impl/PropertiesXfsServiceLookupImpl.java](url) load the name of the file is 'services.properties'. 
Please confirm whether these two files are the same file?

**Comment by AndreasFagschlunger** [comment]
Hello James!

Basically they are the same. In `at.o2xfs.xfs.service` it's a feature to open and register services automatically. This may be convenient, but in order to display the status/outcome for open and register `o2xfs-operator` utilizes it's own properties file.

**Comment by jifffffy** [comment]
Thank you for your reply！
I encountered two problem:
1. In `at.o2xfs.xfs.service`  it opens all services by default.  I want to open only a special service.
2. In `at.o2xfs.operator` , The result of the task is displayed on the UI. I want to get the result in my own thread.
Could you provide some suggestions?

**Comment by AndreasFagschlunger** [comment]
Hello!

As long as you don't provide a proper configuration (`xfs.properties` with `XfsServiceLookup.Class` entry), `at.o2xfs.xfs.service` shouldn't open any service per default.

So you have to call `XfsServiceManager.openAndRegister(String, Class<? extends XfsService>)` by yourself, which is exactly what `at.o2xfs.operator` does in its `XfsStartUpTask`.

**Comment by jifffffy** [comment]
Thanks, I will try it!
