### ISSUE TITLE
CIM, CDM devices. difference between banknotes and coins.

### ISSUE THREAD

**Issue by VitalyEG** [AndreasFagschlunger/O2Xfs#59]
Hi, @AndreasFagschlunger.
I do not understand how to identify devices containing banknotes or coins for CIM-class, CDM-class?  Can I recognize what device contains (banknotes or coins)?

**Comment by AndreasFagschlunger** [comment]
Hi @VitalyEG 
Both, `at.o2xfs.xfs.v3_00.cim.Capabilities3` and `at.o2xfs.xfs.v3_00.cdm.CdmCaps3`, have a `getType` method which will return one of the following values:

Value         | Meaning
----------------|-----------------------------------------
TELLERBILL      | The CIM is a Teller Bill Acceptor.
SELFSERVICEBILL | The CIM is a Self-Service Bill Acceptor.
TELLERCOIN      | The CIM is a Teller Coin Acceptor.
SELFSERVICECOIN | The CIM is a Self-Service Coin Acceptor.

**Comment by VitalyEG** [comment]
Great Thanks, AndreasFagschlunger!
