### ISSUE TITLE
Everywhere where you used wrong removing objects from arraylist.

### ISSUE THREAD

**Issue by VitalyEG** [AndreasFagschlunger/O2Xfs#65]
Everywhere where you used removing object from arraylist wrong:
		for (int i = 0; i < XXX.size(); i++) {
			Object XX = XXX.remove(i);
**...**

**As Example (Wrong):**
    List<String> arrayList = new ArrayList<>();
    arrayList.add("A");
    arrayList.add("B");
    arrayList.add("C");
    arrayList.add("D");
    arrayList.add("E");
    for (int i = 0; i < arrayList.size(); i++) {
      String str = arrayList.remove(i);
      System.out.println("str="+ str);
    }
RESULT:
**str=A
str=C
str=E**

**Please use construnction:**

_Iterator<X> iterator = arrayListX.iterator();
while (iterator.hasNext()) {
      X xx = iterator.next();
      iterator.remove();
}_

**Comment by VitalyEG** [comment]
IssuerToCardScriptProcessing.extractScriptID
TaskMAnager.execute
XRequestWatchdog.checkRequests

**Comment by AndreasFagschlunger** [comment]
I agree it would be cleaner, though it shouldn't do any harm (e.g. `ConcurrentModificationException`). The remove in `IssuerToCardScriptProcessing.extractScriptID` is valid, since it returns the removed object, the other two however may skip items since the index doesn't get decremented.

**Comment by VitalyEG** [comment]
I channged code at XRequestWatchdog.checkRequests:

  _private void checkRequests() {
    final String method = "checkRequests()";
    final long currentTime = System.currentTimeMillis();
    Iterator<Request> iterator = requests.iterator();
    while (iterator.hasNext()) {
      Request request = iterator.next();
      if (request.getTimeoutTime() > currentTime) {
        continue;
      }
      long activeTime = request.getTimeoutTime() - request.startTime;
      if (request.cancelled) {
        if (LOG.isWarnEnabled()) {
          LOG.warn(
            method,
            "Request "
            + request.requestId
            + " has been cancelled but is still active, terminate ...");
        }
        iterator.remove();
        requestQueue.terminateRequest(request.requestId);
      } else {
        if (LOG.isWarnEnabled()) {
          LOG.warn(method, "Request " + request.requestId
            + " has been active for " + activeTime
            + " milliseconds and may be hung, try cancel ...");
        }
        request.cancelled = true;
        requestQueue.cancelRequest(request.requestId);
      }
    }
  }_

and TaskMAnager.execute at:
  _public void execute(final Task task) {
    final String method = "execute(Task)";
    if (LOG.isDebugEnabled()) {
      LOG.debug(method, "task=" + task + ",taskPath=" + taskPath);
    }
    Iterator<Task> iterator = taskPath.iterator();
    while (iterator.hasNext()) {
      Task activeTask = iterator.next();
      activeTask.getCommands().removeCommandsChangedListener(this);
      activeTask.getContent().removeUIContentListener(this);
      iterator.remove();
    }
    internalExecute(task);
  }_

**Comment by AndreasFagschlunger** [comment]
Please consider submitting a [pull request](https://help.github.com/articles/fork-a-repo/) for feature improvements.
