### ISSUE TITLE
[at.o2xfs.xfs.win32] XfsCharArray.set(char[] value): possible ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by jifffffy** [AndreasFagschlunger/O2Xfs#72]
If length of the value less than XfsCharArray's length, possible  ArrayIndexOutOfBoundsException.
https://github.com/AndreasFagschlunger/O2Xfs/blob/f1e682ae340304a7776554ae64ca5106b67922ad/at.o2xfs.xfs/src/main/java/at/o2xfs/xfs/win32/XfsCharArray.java#L47-L53

**Comment by AndreasFagschlunger** [comment]
In this case it's intentional, since the allocated memory has a certain size.
