### ISSUE TITLE
"The process cannot access the file because it is being used by another process"

### ISSUE THREAD

**Issue by yongqinn** [AndreasFagschlunger/O2Xfs#76]
Tried to run on operator from start.cmd, however encounter issues.

**Comment by AndreasFagschlunger** [comment]
Hi @yongqinn 
The start.cmd ist very simple and just redirects output streams to a file. Maybe this doesn't work in your case? So try to remove the redirects (>).

Without more information i don't really now what may cause the problem.

**Comment by yongqinn** [comment]
I'm trying at.o2xfs.operator to run on a NCR ATM application.

**Comment by yongqinn** [comment]
how do I start the GUI from at.o2xfs.operator?
