### ISSUE TITLE
Provide SIU SetGiudLight  A simple usage Example

### ISSUE THREAD

**Issue by jifffffy** [AndreasFagschlunger/O2Xfs#78]
Hi,
I encountered a problem when I created a command that does not exist and needs your help.
I create a SIUSetGuidLightCommand 
https://github.com/sunyuyangg555/O2Xfs/blob/9109f05a5aa14414d1d6db19499e5e3d664e2cbd/at.o2xfs.xfs.service/src/main/java/at/o2xfs/xfs/service/siu/execute/SIUSetGuidLightCommand.java#L20
 with a struct
https://github.com/sunyuyangg555/O2Xfs/blob/9109f05a5aa14414d1d6db19499e5e3d664e2cbd/o2xfs-xfs3/src/o2xfs-xfs310/java/at/o2xfs/xfs/v3_10/siu/SetGuidlight310.java#L40 , 

 when I executed this command.
`
SetGuidlight310.Builder builder = new SetGuidlight310.Builder(RECEIPTPRINTER, SLOWFLASH);
SIUSetGuidLightCommand setGuidLightCommand = new SIUSetGuidLightCommand(builder.build(), siuService);
`
I got the SYNTAX(-802) error:
- 2019-06-12 15:53:11 [Thread-84]DEBUG: at.o2xfs.xfs.XfsAPI.wfsAsyncExecute(HSERVICE, DWORD, Type, DWORD, HWND): hService=10,dwCommand=806,lpCmdData=at.o2xfs.xfs.v3_10.siu.SetGuidlight310@bbd54c[guidLight=RECEIPTPRINTER,command=SLOWFLASH],dwTimeOut=0,hWnd=0606E700
- 2019-06-12 15:53:11 [MessageHandler]DEBUG: at.o2xfs.xfs.util.MessageHandler.callback(int, Buffer): msg=1032,lpWFSResult=at.o2xfs.win32.impl.Win32Buffer@d94da2[size=4,address=60F52118]
- 2019-06-12 15:53:11 [MessageHandler]DEBUG: at.o2xfs.xfs.service.XfsServiceManager.callback(XFSMessage, WFSResult): msg=WFS_EXECUTE_COMPLETE,wfsResult=at.o2xfs.xfs.WFSResult@6435b[requestID=45,service=10,timestamp=at.o2xfs.win32.SYSTEMTIME@1370ae9[types=[2019, 6, 3, 12, 15, 53, 11, 10]],result=-802,u=at.o2xfs.win32.Union@16509c2[size=4,fields={commandCode=806,eventID=806}],buffer=Address: 7231C17D, Value: 00000000]
- 2019-06-12 15:53:11 [MessageHandler]DEBUG: at.o2xfs.xfs.service.EventDispatcher.dispatch(XFSMessage, IXfsEventNotification, WFSResult): xfsMessage=WFS_EXECUTE_COMPLETE,eventNotification=at.o2xfs.xfs.service.siu.execute.SIUSetGuidLightCommand@d38af7,wfsResult=at.o2xfs.xfs.WFSResult@6435b[requestID=45,service=10,timestamp=at.o2xfs.win32.SYSTEMTIME@1370ae9[types=[2019, 6, 3, 12, 15, 53, 11, 10]],result=-802,u=at.o2xfs.win32.Union@16509c2[size=4,fields={commandCode=806,eventID=806}],buffer=Address: 7231C17D, Value: 00000000]
- 2019-06-12 15:53:11 [MessageHandler]DEBUG: at.o2xfs.xfs.service.cmd.AbstractAsyncXfsCommand.fireOperationCompleteEvent(WFSResult): wfsResult=at.o2xfs.xfs.WFSResult@6435b[requestID=45,service=10,timestamp=at.o2xfs.win32.SYSTEMTIME@1370ae9[types=[2019, 6, 3, 12, 15, 53, 11, 10]],result=-802,u=at.o2xfs.win32.Union@16509c2[size=4,fields={commandCode=806,eventID=806}],buffer=Address: 7231C17D, Value: 00000000]

so how should I pass the parameters(wGuidLight, fwCommand)?
I would be very grateful if there is an example.

**Comment by AndreasFagschlunger** [comment]
In `SetGuidlight310` you are using `Xfs(D)Word` where it should only be `XfsWord`:
```
typedef struct _wfs_siu_set_guidlight
{
	WORD            wGuidLight;
	WORD            fwCommand;
} WFSSIUSETGUIDLIGHT, *LPWFSSIUSETGUIDLIGHT;
```

**Comment by jifffffy** [comment]
Thank you very much, I didn't notice the D.
