### ISSUE TITLE
SetGuidLightCommand

### ISSUE THREAD

**Issue by Matiasqj** [AndreasFagschlunger/O2Xfs#85]
Hi , I cant use the guidlight command, I try to create a new SetGuidLight3, but I cant add the commands to execute the SIUCommand, can you help me with this? How I can add the command?

**Comment by AndreasFagschlunger** [comment]
Sorry for the late response. The old classes don't always have a constructor for "writing" structures, mostly only for reading, I try todo things better in `o2xfs-xfs3-api` project, but it contains only CDM for the moment.
In your case I suggest to add a constructor like this:

```java
	public SetGuidLight3(SIUGuidLight guidLight, SIUGuidLightPortState command) {
		this();
		allocate();
		this.guidLight.set(guidLight);
		this.command.set(command);
	}
```

**Comment by Matiasqj** [comment]
Thanks !!!
