### ISSUE TITLE
JFrog repository URL changed

### ISSUE THREAD

**Issue by jifffffy** [AndreasFagschlunger/O2Xfs#86]
I find JFrog repository URL need to change from https://repo.fagschlunger.co.at/libs-snapshot-local  to https://repo.fagschlunger.co.at/artifactory/libs-snapshot-local.

**Comment by AndreasFagschlunger** [comment]
Yes, you're right. A little background to this:
https://jfrog.com/knowledge-base/how-to-remove-artifactory-from-the-context-url-in-artifactory-7/
So I guess I just stick with "artifactory" within the context URL.
