### ISSUE TITLE
How can I get the details of hardware error from description of results in WFS_SYSE_HARDWARE_ERROR

### ISSUE THREAD

**Issue by sundarsabapathi** [AndreasFagschlunger/O2Xfs#92]
Hi @AndreasFagschlunger

I am trying to get hardware error details from description of results in WFS_SYSE_HARDWARE_ERROR for a device.
```
typedef struct _wfs_hwerror {
   LPSTR lpszLogicalName;
   LPSTR lpszPhysicalName;
   LPSTR lpszWorkstationName;
   LPSTR lpszAppID;
   DWORD dwAction;
   DWORD dwSize;
   LPBYTE lpbDescription;
} WFSHWERROR, *LPWFSHWERROR;


```

I want to know what information would be available in `lpbDescription` and how to interpret it.

Currently I got the below information from this how do I know the  problem 

```
{
        "dwAction": 16,
        "lpszAppID": "",
        "lpbDescription": 83,
        "lpszLogicalName": "IDC",
        "lpszPhysicalName": "XFS IDC Service Provider",
        "dwSize": 141,
        "lpszWorkstationName": "9M1EB5IPMQV"
 }
```

**Comment by AndreasFagschlunger** [comment]
Hi @sundarsabapathi

The content of "lpbDescription" is not part of XFS specification, so it depends on the service provider which information is provided and how it can be interpreted.

If the "lpbDescription" doesn't contain useful information, I suggest you check the logs of the service provider, maybe even the Windows Event log.

**Comment by sundarsabapathi** [comment]
Thanks @AndreasFagschlunger. I check the logs of the service provider.
