### ISSUE TITLE
[at.o2xfs.xfs.siu] Should the constructor of SIUSensorsStatus be public?

### ISSUE THREAD

**Issue by sundarsabapathi** [AndreasFagschlunger/O2Xfs#93]
Hi @AndreasFagschlunger 
May I know why the constructor of  SIUSensorsStatus is protected while other such status classes have public constructors.

**Comment by AndreasFagschlunger** [comment]
I don't really remember, I think i simply didn't need it at the time. But honestly, I changed the whole approach on howto handle Structs and the mapping between Java and C/C++, e.g.:
https://github.com/AndreasFagschlunger/o2xfs-xfs3-api/tree/develop/src/main/java/at/o2xfs/xfs/v3/cdm

A XFS Structs doesn't need to extend from a super class Struct anymore, it's a simple POJO and more serialized and deserialized into a native memory. The huge advantage is, that the application then doesn't have to deal with freeing up native memory. The POJOs are simply filled with data from native memory, but the POJO itself is allocated by the JVM like any other java object.

So the O2Xfs repository is deprecated in my eyes and the new stuff is shattered into many repositories. The thing is, I don't really find the time to work on the project as I used to. But I did managed to create my own SPI and application at the same time and did a full cash transaction. So the concept itself is working fine.

But to really move forward it would be necessary to develop a service provider which can then be used to develop the application and run automated tests. And if you have a virtual ATM, you need some fancy GUI to control everything. And then there is already XFS for IoT, which uses WebSockets. A translation from XFS 3 to XFS IoT would be interesting.

So there are a lot of possibilities to move forward, but I don't find the time at the moment.

**Comment by sundarsabapathi** [comment]
Thanks @AndreasFagschlunger for your kind explanation.
