### ISSUE TITLE
Publish the artifacts to maven central 

### ISSUE THREAD

**Issue by sundarsabapathi** [AndreasFagschlunger/O2Xfs#94]
Hi @AndreasFagschlunger 
It would be great if the projects artifacts are available in maven central. Please let me know if I can be of any help. I would be glad to contribute.

**Comment by AndreasFagschlunger** [comment]
As I mentioned in issue #93, the O2Xfs is already outdated. And it's all early development. So I don't really see the progress of the project or the quality at a level, where it could be published as a release version on maven. I put some time and afford into setting up my own maven repository (repo.fagschlunger.co.at). Also the projects itself use Gradle. So neither building on your own nor using a additional maven repository should be that difficult.

**Comment by sundarsabapathi** [comment]
Thanks @AndreasFagschlunger  for your kind explanation.
